name: CI Build PR

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup sdk
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Run tests
        run: mvn test